### ISSUE TITLE
client session blocks requests from server

### ISSUE THREAD

**Issue by torres98** [obgm/libcoap#1363] opened 2024-04-23 07:36 UTC
## Environment

- Build System:            CMake
- Operating System:         Ubuntu
- Operating System Version: 22.04 LTS
- Hosted Environment:      None

## Problem Description

In one of my use-cases, I have an aiocoap process hosting a single server instance (let's say listening to 127.0.0.1:5000) and a libcoap process hosting a client and a server (obviously on two separate threads, and with different contexts) in order to interact with the first one. The idea is that the aiocoap server handles requests sent by the libcoap client and sends some requests itself to the libcoap Server (in case you are not aware, the aiocoap library for python allows you to create a server that can also send requests).

I found out that, if I just create a client session (using `coap_new_client_session()`) towards the aiocoap server (so with destination address 127.0.0.1:5000) and keep it alive for the whole interaction, the requests coming from that address towards the libcoap server are not dispatched to the server handler function. Furthermore, no log message is shown regarding those requests (even at log level Debug). I have checked through Wireshark that such requests are actually being sent, so the problem is definitely not on the aiocoap side. If I keep alive the client session only when sending something, the requests get processed as intended by the libcoap server. Also, if I send those requests using a new client through aiocoap (so using a different source address) instead of the server, the requests get correctly handled as well.

I have looked at the docs extensively, but this behaviour is not mentioned anywhere and it looks like to me this is unintended. 

### Expected Behavior

I would expect those requests to be processed correctly.

### Actual Behavior

Those requests are not even detected at all.

### Code to reproduce this issue

I feel like this may not be needed. If that's not the case, let me know and I will provide you a minimal example.

**Comment by mrdeep1** [comment] 2024-04-23 09:03
4.3.4 does not have the thread safe code, so that is unlikely to be the issue.

So, the libcoap server is listening on port X (different to the source port or the libcoap client), wire shark shows the packets being sent to port X.  All I can immediately think of is a firewall wall that is not allowing the inbound connection from the aiocoap module.

**Comment by torres98** [comment] 2024-04-23 09:10
Yes, but consider that I do not have any firewall set up, plus it is enough to do any of the two things mentioned in the post (use a new aiocoap client/shutting down the libcoap client session) to make it work fine.

My (uneducated) guess is that, since the coap client session is bound to send requests to port X, internally libcoap doesn't pass this request to the Server queue. I feel like it gets treated as a response intended for the client. 

This would also explain why no debug message is shown for such requests: when such a request arrives, thread#1 (so the client) is not polling through coap_io_process, and therefore the request isn't even picked up. Do you think this may be plausible?

**Comment by mrdeep1** [comment] 2024-04-23 09:23
OK.  Is the libcoap and aiocoap process running on the same server?

libcoap client src port A, dst port B
libcoap server listening port C
aiocoap server listening port B
aiocoap server (as client after getting request) src port D, dst port C

If D == B, then it is possible ubuntu stack is getting messed up.
When in the 'hung' state, does starting up a new, separate aiooap client work as expected?

**Comment by torres98** [comment] 2024-04-23 09:33
Every client/server is run on localhost (127.0.0.1), and yes, D == B.

> When in the 'hung' state, does starting up a new, separate aiooap client work as expected?
Do you mean, after sending a request that hangs through the aiocoap server, if I have tried to create an aiocoap client and send the same request (but ofc with a different src port)?

**Comment by mrdeep1** [comment] 2024-04-23 09:37
> Do you mean, after sending a request that hangs through the aiocoap server, if I have tried to create
> an aiocoap client and send the same request (but ofc with a different src port)?

Yes, start a different aiocoap application from your server/client application (or use the libcoap examples/coap-client).

**Comment by torres98** [comment] 2024-04-23 09:40
Kind of, I have checked wheter the server was able to receive requests at all but using the following executable (https://github.com/kb2ma/cotel). The libcoap server was receiving and processing the request without issues. But i haven't tried using specifically an other aiocoap client alongside the aiocoap server in the "hang" state.

**Comment by mrdeep1** [comment] 2024-04-23 10:02
The fact that you are using a different client, and that works, tells me that the libcoap client/server server component is working.  The issue is with the ubuntu networking stack not liking `D == B` port conflict.

For UDP, libcoap does a `connect()` call (in `coap_socket_connect_udp()`), so that the `src IP/src Port, dst IP/ dst Port, UDP` tuple are maintained over time for a CoAP session.  So, Port B will have significance here when trying to use it for a different tuple.

**Comment by torres98** [comment] 2024-04-23 10:25
I understand. So if I want my use-case to work I should not keep the client session alive I suppose.

**Comment by mrdeep1** [comment] 2024-04-23 11:00
Yes.  Or tweak aiocoap to use a different src port from B when acting as a proxy server.
[It is possible to use the libcoap examples coap-server as a proxy server if you want instead of aiocoap]

It is unclear to me whether the libcoap client is waiting for a response back from the aiocoap server before it can close that specific CoAP session.  Or it is just a fire and forget?

**Comment by mrdeep1** [comment] 2024-04-23 11:48
Ok - it look like you have to fire off the client request, wait for a response and then close the client's session using `coap_session_release()` - which then leaves the coap_context around which can then be used for the next client request.  Otherwise, you will need to use `coap_free_context()`.

**Comment by torres98** [comment] 2024-04-23 12:27
I thought so... if you feel like it, you can close the issue then.

**Comment by mrdeep1** [comment] 2024-04-23 15:02
Thank for using libcoap.  I will close this issue now.

**Closed** 2024-04-25 13:48 UTC
