### ISSUE TITLE
Multi CoAP Client using libcoap in observer mode

### ISSUE THREAD

**Issue by FelicxFoster** [obgm/libcoap#573] opened 2020-11-25 08:16 UTC
I use two client to receive server's message in observer mode. However I got the error as follow:

1、Start the first client, the client and server can communicate normally.
2、Then start the second client, the first one immediately displays an warning"WARN discard malfomed PDU", and the first one can't receive any data from server. But the second is normal.
3、And in  the coap_log iI found that the server only sent data to the second one, not the first one.

So could you  share me the reason and solution? thx

**Comment by mrdeep1** [comment] 2020-11-25 09:46
I am not able to reproduce your issue.  

What is the version of libcoap (see `coap-client -? 2>&1 | head` output)?
How are you running the coap-server (give the CLI invocation line)?
How are you running the coap-client(s) (Give the CLI invocation line)?

**Comment by FelicxFoster** [comment] 2020-11-25 12:07
How do you test? Could you share your test case? thx

**Comment by obgm** [comment] 2020-11-25 13:02
Your first client's behavior in step 2 suggests that the second client is started in a way that interferes with the first. Do you have a pcap trace?

**Comment by mrdeep1** [comment] 2020-11-25 13:53
I vaguely recall a bug in this area a while back - hence question about which code version you are using - can you please tell us what it is?

Three terminal sessions
1) coap-server
2) coap-client -s 60 coap://127.0.0.1/time
3) coap-client -s 60 coap://127.0.0.1/time

To help you further, please provide
1) a pcap file as requested by obgm
2) the libcoap code version you are using
3) development environment
4) are you using lwIP or Contiki, riot, esp-idf or just a standard linux system?
5) how you invoke the server
6) how you invoke the clients

 If you are using custom code, in particular for the server, test it out using standard utilities where possible - e.g your custom server with the standard coap-client executables.

**Comment by FelicxFoster** [comment] 2020-11-26 07:15
I use the command, and the three terminal sessions were good running. So I guess it isn't the problem of  libcoap code version, maybe my code error.

Here are some answers to your questions:
1. Sorry that I don't understand this question.
2. the libcoap code version: commit 1739507a1eee6f8831ca7221adaa8d5413527b7f
3. Ubuntu and C++
4. Only use a standard linux system
5. the Code invokes the server is as follow:
```cpp
coap_resource_t *resource =
        coap_resource_init(uri, COAP_RESOURCE_FLAGS_NOTIFY_NON);

coap_register_handler(
    resource, COAP_REQUEST_GET,
    [](coap_context_t *ctx, struct coap_resource_t *resource,
        coap_session_t *session, coap_pdu_t *request, coap_binary_t *token,
        coap_string_t *query, coap_pdu_t *response) {
        // Get data
        CoapMessage *msg = reinterpret_cast<CoapMessage *>(
            coap_resource_get_userdata(resource));
        if (msg == nullptr) {
        coap_log(LOG_ERR, "msg is null\n");
        coap_add_data(response, 13, (const uint8_t *)"Invalid value");
        return;
        }
        uint8_t *data = (uint8_t *)(msg->data.c_str());
        size_t len = msg->data.length();

        coap_add_data_blocked_response(resource, session, request, response,
                                        token, COAP_MEDIATYPE_TEXT_PLAIN, 1,
                                        len, data);
        delete msg;
        msg = nullptr;
        resource->user_data = nullptr;
    });

coap_resource_set_get_observable(resource, 1);
coap_add_resource(ctx, resource);
while (1) {
    coap_resource_set_userdata(resource, reinterpret_cast<void *>(msg));
    coap_resource_notify_observers(resource, nullptr);
    coap_io_process(ctx, 10);
}
```
6. the Code invokes the clients is as follow:
```cpp
coap_session_t* session = coap_new_client_session(ctx, nullptr, &dst, COAP_PROTO_UDP);
coap_pdu_t* request = coap_pdu_init(COAP_MESSAGE_CON, COAP_REQUEST_GET,
                                    coap_new_message_id(session),
                                    coap_session_max_pdu_size(session));

size_t len = resource.length();
const uint8_t* data = reinterpret_cast<const uint8_t*>(resource.c_str());

coap_add_option(request, COAP_OPTION_OBSERVE, 0, nullptr);
coap_add_option(request, COAP_OPTION_URI_PATH, len, data);
coap_send(session, request);
```
From coap_observe(3) I found that `The *coap_resource_notify_observers*() function needs to be called whenever the
server application determines that there has been a change to the state of _resource_, possibly only matching a specific _query_ if _query_ is not NULL.` .
I guess the bug is that I use the code`coap_resource_notify_observers(resource, nullptr);` in server. The _query_ is assigned to nullptr, not a specific value.

**Comment by obgm** [comment] 2020-11-26 09:45
@FelicxFoster Regarding 1.: Tools such as tcpdump or wireshark can record frames sent over the network when they cross your system's network interface. They use a format called pcap (or pcapng, respectively) as serialization of the collected sets of recorded packets. Debugging issues with broken or ill-routed packets will become significantly easier if such so-called traces are avaiable.

**Comment by mrdeep1** [comment] 2020-11-26 10:00
Trigger Observe for client no 1 in GET handler sends response and clears resource->user_data.  Then client no 2 is handled in GET handler but has no data to send.  Hence your issue.

**Comment by obgm** [comment] 2020-11-26 10:02
Well, it sends an error message in the payload in this case.
But note that clearing the user_data would break if the client sent a Block2 option (which from the code shown, it doesn't).

**Comment by mrdeep1** [comment] 2020-11-26 10:19
Actually error response is not sent as response->code is not updated (implicitly done in coap_add_data_blocked_response()

**Comment by obgm** [comment] 2020-11-26 13:26
Ah, yes

**Comment by FelicxFoster** [comment] 2020-11-26 14:31
@obgm @mrdeep1 Thank you for your reply, I will modify my code

**Comment by FelicxFoster** [comment] 2020-11-27 03:02
@mrdeep1 Thanks, my problem has been solved.
And I have another code problems. Can the function  `void coap_add_data_blocked_response(coap_resource_t* resource, coap_session_t* session, size_t length, const uint8_t* data)` free data automatically? Or should I free it by myself?

**Comment by mrdeep1** [comment] 2020-11-27 11:53
No, `coap_add_data_blocked_response()` will never release the provided `data`.
PR #554 (not yet merged) has a function `coap_add_data_response_large()` that allows you to define a call-back to release (i.e free off) any data once the `data `has been sent over the wire.

A place to free off any `data` (if not using #554) is just before you update the resource tracked data with the new `data` 
````
while (1) {
    coap_resource_set_userdata(resource, reinterpret_cast<void *>(msg));
````
NEW  (but have no idea as to how you are setting up / updating msg)
````
while (1) {
    free (coap_resource_get_userdata(resource));
    coap_resource_set_userdata(resource, reinterpret_cast<void *>(msg));
````
Also
````
coap_io_process(ctx, 10);
````
I am not sure why you need the timeout to 10ms - it will make network traffic pretty busy.

**Comment by FelicxFoster** [comment] 2020-11-29 02:16
OK， I got it. Thanks  a lot for your reply (again!)

**Closed** 2020-11-29 02:16 UTC
