### ISSUE TITLE
Using coap_transaction_id() for build without WITH_POSIX and WITH_LWIP and WITH_CONTIKI

### ISSUE THREAD

**Issue by PawelWMS** [obgm/libcoap#73] opened 2017-04-03 23:13 UTC
Hi there. We've agreed recently to remove coap_transaction_id() if neither WITH_POSIX, nor WITH_LWIP, nor WITH_CONTIKI is defined. Now I've noticed that coap_transaction_id() is used in places, where these WITH_* macros are not defined leading to build issues. What would you suggest to do in such cases? Cascade-remove all APIs using it, if neither of these macros is there?

Also, do you remember why we didn't want to use coap_transaction_id()? It still seems to be hashing the pdu->hrd->id without any of the macros. Is that not sufficient and that's why coap_transaction_id() shouldn't be used?

**Comment by obgm** [comment] 2017-04-04 08:20
The problem is that the CoAP message id for UDP is only unique within the connection `(src, srcport, dst, dstport)`. For TCP, it does not even exist. 
The function `coap_transaction_id()` is meant to provide a unique identifier for a message that is global within an instance of `coap_context_t` hence a simple hash over the CoAP message id is not sufficient in case the message identifier has been generated elsewhere (typically the remote peer) or does not exist as in the case of TCP.

**Comment by PawelWMS** [comment] 2017-04-04 08:55
Ok. In that case how can a unique ID be generated when neither of these macros is defined? Should the peer's address be used along with the CoAP message ID. If so I can make the API available again and solve the unused parameter issue at the same time.

**Comment by obgm** [comment] 2017-04-04 09:01
Yes, IMHO this is the cleanest solution.

**Comment by PawelWMS** [comment] 2017-04-04 09:16
Ok, but what will be the proper way to do it? And when I looked at the function closer, it seems that coap_address_t is not available when none of the macros is defined. Is this expected behavior?

**Comment by obgm** [comment] 2017-04-04 09:25
Yes, every support platform must define `coap_address_t` in a way that can be used as transport address. In principle, posix should be the default. But for now, when running configure, you will always end up with WITH_POSIX defined.

**Comment by PawelWMS** [comment] 2017-04-04 09:32
I see now the source of confusion and it's my fault - I apologize. I've been working in parallel on your libcoap and the one from dthaler's fork, which makes libcoap work for Windows and this one particular source of a W4 warning, which I was trying to remove, was actually only one missed "#if defined" in that fork and not your repo. Please give me a few minutes to fix your code.

**Comment by PawelWMS** [comment] 2017-04-04 09:39
Here's the [pull request](https://github.com/obgm/libcoap/pull/74).

**Comment by obgm** [comment] 2017-04-04 10:11
Excellent, merged :-)

**Comment by obgm** [comment] 2017-04-06 09:06
Closing as resolved.

**Closed by obgm** 2017-04-06 09:06 UTC
