### ISSUE TITLE
Error in transferring large data using block mode transfer !!

### ISSUE THREAD

**Issue by Koushik-ak47** [obgm/libcoap#1524] opened 2024-09-24 10:58 UTC
- I have read the documentation [libcoap Modules Documentation](https://libcoap.net/doc/reference/develop/modules.html)
and the issue is not addressed there.
-  I have read the documentation [libcoap Manual Pages](https://libcoap.net/doc/reference/develop/manpage.html)
and the issue is not addressed there.
- I have updated my libcoap branch (develop) to the latest version and
checked that the issue is present there.
- I have searched the [Issue Tracker](https://github.com/obgm/libcoap/issues)
(both open and closed - overwrite `is:issue is:open`) for a similar issue and
not found a similar issue.
- I have checked the [Wiki](https://github.com/obgm/libcoap/wiki) to see if
the issue is reported there.
- I have read the HOWTOs provided with the source.
- I have read the [BUILDING](https://raw.githubusercontent.com/obgm/libcoap/develop/BUILDING)
on how to build from source.

## Environment

- Build System:             [ARM GCC]
- Operating System:         [Embedded Linux]
- Operating System Version: [ Ubuntu 20.04 LTS]
- Hosted Environment:    Server application run on ARM processor embedded device

## libcoap Configuration Summary

If get_config,sh exists, please copy the output from (do in the top level libcoap directory) :-
```
./get_config.sh
libcoap package version        : "4.3.5rc3"
libcoap package source         : "4.3.5rc3"
libcoap API version            : "3"
libcoap ABI version            : "3.1.2"
libcoap libtool SO version     : "4.2.1"
libcoap DTLS lib extn          : "-mbedtls"
host system                    : "x86_64-pc-linux-gnu"
build with server support      : "yes"
build with client support      : "yes"
build with proxy support       : "yes"
build with IPv4 support        : "yes"
build with IPv6 support        : "yes"
build with Unix socket support : "yes"
build with TCP support         : "yes"
build DTLS support             : "yes"
   -->  Mbed TLS around        : "yes" (found Mbed TLS 2.16.3 without pkg-config)
        MbedTLS_CFLAGS         : ""
        MbedTLS_LIBS           : "-lmbedtls -lmbedcrypto -lmbedx509"
add default names              : "yes"
build Observe Persist          : "yes"
build using epoll              : "yes"
enable small stack size        : "no"
enable separate responses      : "yes"
enable OSCORE support          : "yes"
enable Q-Block support         : "yes"
enable max logging level       : "none"
enable thread safe code        : "yes"
enable recursive lock check    : "yes"
build doxygen pages            : "yes"
    --> Doxygen around         : "yes" (/usr/bin/doxygen 1.8.17)
       -->  dot around         : "no" (DOT not found!)
build man pages                : "yes"
build unit test binary         : "no"
build examples                 : "yes"
install examples source        : "yes"
build with gcov support        : "no"
build shared library           : "yes"
build static library           : "yes"
```

## Problem Description

**Incomplete transmission of large data (greater than 300MB) using block mode transfer from coap client to server when the server is deployed in a hardware device and connected to client over an ethernet network. The client stops the transmission after a certain number of blocks.**

### Expected Behavior

All blocks should be transferred to server.

### Actual Behavior

The transmission of packets/blocks is being stopped even after the server sent the response code of CONTINUE for the previous block and i observed re-transmission of blocks as well after certain time period. For example: I tried to send 300MB data from a that means client has to send 307200 blocks of each 1KB. The client starts **retransmission** of data approximately block num: 65535 (60MB) and halts around **100MB-200MB.** 

### Steps to reproduce

1. Create the basic setup of coap client like context, binding address, session, resource pdu, method , block mode etc on the client side.
2. Create the basic setup of coap server like context, binding address, port , session, endpoint, pdu, handler of the pdu.
3. On client side, extract data into a string form a txt file and pass the string as data to the coap application API coap_add_data_large_request() .
4. On server side, the request handler will triggered when the data is sent with the same uri-path in which data is retreived using coap_get_data_large() and storing it in the bodybuffer using coap_build_block_body(). It will send the response code of CONTINUE/CREATED based upon the logic mentioned in the documentation manual pages (payloadlen+offset <= total).  

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed
better.

//client
#include "coap3/coap.h"

void main()
{
// initial code setup code should be written here and assume char *buffer has the large data  //
    coap_str_const_t *largedata = coap_new_str_const((const uint8_t *)buffer, buff_len);
    printf("large data size is: %lu\n", largedata->length);
    
    if(coap_add_data_large_request(session, request, buff_len, largedata->s, NULL, NULL) != 1){
      printf("error in sending data");
    }
   while(1){
   coap_io_process(ctx, COAP_IO_WAIT); // i tried the timeout by increasing it to 10 minutes.
   }
}

//server receive handler code:
coap_binary_t *bodybuffer = NULL;

void receive_handler(coap_resource_t *resource,
                                      coap_session_t *session,
                                      const coap_pdu_t *request,
                                      const coap_string_t *query,
                                      coap_pdu_t *response)
{

  uint8_t *payloadBuffer;
  size_t payloadlen = 0;
  size_t offset = 0;
  size_t total ;
  
  if(coap_get_data_large(request, &payloadlen, (const uint8_t **)&payloadBuffer, &offset, &total) != 0 && (payloadlen != total))
  {

    bodybuffer = coap_block_build_body(bodybuffer, payloadlen, (const uint8_t*)payloadBuffer, offset, total);
    if(!bodybuffer)
    {
       printf("building block error\n");
       return;
     }
    else{
       printf("added blocks to body\n");
    }
      
    count++;
    printf("the count of chunk is: %lu\n", count);

    if(offset+payloadlen < total){
      coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTINUE);
    }
    else if(offset+payloadlen == total){

      coap_pdu_set_code(response, COAP_RESPONSE_CODE_CREATED);
      //add_data_to_file(filename, bodybuffer->s);
      printf("completed retreiving the complete data into body\n");
      count = 0;
    }

  }
  else{
    if(payloadlen == total){
      printf("len and total are same\n");
    }
    printf("getting large data error\n");
  }

}


```
I tried increasing the timeout to higher values and still faced the same issue on the setup mentioned but it is working on local ip address on my linux desktop. I am able to see retransmission of blocks as well.
[put_large_data_failed_evidence.zip](https://github.com/user-attachments/files/17112924/put_large_data_failed_evidence.zip)

## Debug Logs

Please check the **wireshark** log of CoAP protocol which gives more information about blocks. Please apply coap protocol as filter for better understanding. 

## Other items if possible

My server and client runs in loopback on laptop perfectly. But issues starts when server is ported on this arm embedded device and when I tried to send larger files like 100MB, we see re-transmission issues which I suspect to be the issue. File transfer success for lower size like 40MB. 
Not sure how and where to debug.
Kindly help and thanks in advance.

**Comment by mrdeep1** [comment] 2024-09-24 11:52
>  I am able to see retransmission of blocks as well. I am able to see retransmission of blocks as well.

This is because the same token is used after 65535 packets are sent (left 2 bytes of token are incremented per packet sent and wrap back to 0 after 65535 bytes - see record 137261) so this is not your issue as the server is supposed to be treat tokens opaquely.

Have you tried uploading your large file using the examples coap-client (with -B set a value of 10000 - your example session stops after 385 seconds) ?

**Comment by Koushik-ak47** [comment] 2024-09-24 16:01
Yes, I checked out the coap-client and coap-server example codes and have gone through the option "-B" value which sets the timeout value to of coap_io_process(ctx, timeout). So, i changed the timeout value to 10 mins (1200*1000 ms) in my code snippet itself which replicates the same. But I am still getting error. Currently I used coap log and got the finding that the **lg_srcv lg_xmit, lg_crcv structs have been released** in the last block that has been transferred.

**Comment by mrdeep1** [comment] 2024-09-25 07:57
From the packet trace, it was the client that stopped sending.

`lg_srcv `should only be used by the server, and so likely that this timeout /release occurred after the client stopped transmitting.

`lg_xmit `is used by the client (and can be used by a server) to handle the transmission of multiple blocks until they are all transmitted or there is a failure of some sort.

`lg_crcv `is used by the client after the end of the request transmission to handle any multi-block response.

It would be good to know what is in the client log at the start of the transmission (where the `lg_xmit `and `lg_crcv `are set up) as well as at the end of the transmission where the `lg_xmit` and `lg_crcv `structures are released.

**Comment by mrdeep1** [comment] 2024-09-25 08:02
>  I checked out the coap-client 

It would be good to know what options you used on the command line here.  I am assuming this failed as well as your code.

**Comment by mrdeep1** [comment] 2024-09-25 12:48
I have transferred a 1G file with no issues (took 12 minutes) (1G is about the largest that can be transferred with only 20 bits worth of 1K blocks available as per RFC7959), using
````
examples/coap-client -m put -f 1Gfile coap://192.168.0.88/example_data -v7 -x -B 5000
````
See #1525 which contains a fix so that tokens during a large transfer do not get re-used.  It also provides a mechanism for not displaying the data whenever `coap_show_pdu() `is called.

**Comment by Koushik-ak47** [comment] 2024-09-29 07:49
> I have transferred a 300MB file using the command you mentioned, but still the problem occured. I have seen in debug logs that lg_srcv in server is being released first and then the client trys to send the block for which it doesn't get any block. So, it releases the xmit and crcv buffer as well on client side. 

> ```
> examples/coap-client -m put -f 1Gfile coap://192.168.0.88/example_data -v7 -x -B 5000
> ```

>  So, I have added some custom signature logs in all the call heirarchy to know why coap_block_delete_lg_srcv() is being called and got to know its being called from coap_io_prepare_io / coap_block_check_lg_srcv_timeouts/coap_block_delete_lg_srcv. 
![evidence new build libcoapserver_1](https://github.com/user-attachments/assets/95a46bcd-ca61-4a81-bdea-e618cc1a6715)

I am not able to control the timeout using -B 5000. Please give some inputs to solve this issue.

**Comment by mrdeep1** [comment] 2024-09-29 17:04
The server has had a `lg_srcv `timeout, and so sends back the 2.31 Continue, but without the Block2 option, so the client does not send the next block as it is not told what the latest received block is.   I missed that in the pcap trace - sorry.

We need to track down this `lg_srcv `timeout as it is the root cause of traffic stopping.

It would be good to know where you had put your 2 AK47 debug statements in the code (e.g. in which function).
What value are you reporting for the srcv_io_timeout ?

It would be good to confirm the version of the server code you have compiled for the ARM processer, which could be earlier than the 4.3.5rc3 you reported.

For the ARM processor - is it 32 bits ? I am wondering whether we have a register overflow here.

What is the host OS you are using for the ARM processor?

**Comment by Koushik-ak47** [comment] 2024-09-30 06:06
> We need to track down this `lg_srcv `timeout as it is the root cause of traffic stopping.
> It would be good to know where you had put your 2 AK47 debug statements in the code (e.g. in which function). What value are you reporting for the srcv_io_timeout ?

The first AK47 srcv_timeout is added (just before the coap_block_delete_lg_srcv() call ) in the function coap_block_check_lg_srcv_timeouts() located in coap_block.c src file. 

The second AK47 srcv_io_timeout is added in the coap_io_prepare_io_lkd in version 4.3.5 and coap_io_prepare_io in version 4.3.4. The number I was printing is just a line number.
````
if (s->lg_srcv) {
          if (coap_block_check_lg_srcv_timeouts(s, now, &s_timeout)) {
            if (timeout == 0 || s_timeout < timeout)
              timeout = s_timeout;
          }
          else{
            coap_log_debug("AK47 srcv_io_timeout == %d\n", __LINE__);
          }
}
`````
 
> It would be good to confirm the version of the server code you have compiled for the ARM processer, which could be earlier than the 4.3.5rc3 you reported.
> 
> For the ARM processor - is it 32 bits ? I am wondering whether we have a register overflow here.
> 
> What is the host OS you are using for the ARM processor?

Yes, the server libcoap-3 version is 4.3.4 , Linux OS and the ARM processor is of 64 bit (ignore the timestamp in the below terminal output)
````
Linux imx8mm-cgt-sx8m-ak47 5.15.32-congatec+g81e44e2b14da #1 SMP PREEMPT Wed Jun 7 12:09:02 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
````

**Comment by mrdeep1** [comment] 2024-09-30 08:55
For the ARM processor, can you please try using 4.3.5 (or the develop branch where coap_enable_pdu_data_output() was added to give the ability to suppress the data output in the logs).  I think your server issue was fixed post 4.3.4 in #1362 where there is an additional update to `lg_srcv->last_used`.

**Comment by mrdeep1** [comment] 2024-10-08 09:41
@Koushik-ak47 Do you need any more help on this, or can this be closed now?

**Comment by Koushik-ak47** [comment] 2024-10-08 09:46
Hi @mrdeep1 , we can close the ticket. I have updated the version to libcoap 4.3.4 to 4.3.5 on my ARM processor which you have guided me and the issue got solved. Thank you for your constant and immediate help.

**Comment by mrdeep1** [comment] 2024-10-08 09:55
Thanks.

**Closed as completed by mrdeep1** 2024-10-08 09:55 UTC
