### ISSUE TITLE
Log level definitions in coap_debug.h conflict with syslog.h

### ISSUE THREAD

**Issue by franzhollerer** [obgm/libcoap#749] opened 2021-09-20 11:38 UTC
I found that the LOG_* definitions in coap_debug.h conflict with syslog.h.

The following code:

```c
     1  #include <syslog.h>
     2  #include <coap3/coap.h>
     3
     4  int main(int argc, char **argv)
     5  {
     6      return 0;
     7  }
```

Results in the following error:

```bash
In file included from /usr/include/syslog.h:1,
                 from coap_syslog.c:1:
/usr/local/include/coap3/coap_debug.h:52:3: error: expected identifier before numeric constant
   52 |   LOG_EMERG=0, /**< Emergency */
      |   ^~~~~~~~~
```
The problem is that syslog.h defines log levels with identical name. IMHO as syslog is specified in POSIX, the conflicting definitions in libcoap should be renamed.

**Comment by obgm** [comment] 2021-09-20 11:50
This works as intended. The conflicting definitions are done only if you do not have `syslog.h` (i.e., `HAVE_SYSLOG_H` is not defined).

**Comment by mrdeep1** [comment] 2021-09-20 12:07
That is the case when building libcoap library where the autoconf process defines `HAVE_SYSLOG_H`.  Unfortunately, it does not work for the libcoap examples with the following change
````
diff --git a/examples/coap-client.c b/examples/coap-client.c
index 243b64a..000063e 100644
--- a/examples/coap-client.c
+++ b/examples/coap-client.c
@@ -43,6 +43,7 @@ static char* strndup(const char* s1, size_t n)
 #include <netdb.h>
 #endif
 
+#include <syslog.h>
 #include <coap3/coap.h>
 
 #define MAX_USER 128 /* Maximum length of a user name (i.e., PSK
````
`include/coap3/coap_debug.h` needs to check if, say, `LOG_EMERG `is not defined, and if not, then skip the LOG_* enum definition.

I can come up with a fix for this later today.

**Comment by franzhollerer** [comment] 2021-09-20 12:12
Hm, but I have a syslog.h in my system, and I have included it before coap3/coap.h. Well, okay. The example compiles if I call the compiler with:

```bash
$ gcc -DHAVE_SYSLOG_H coap_syslog.c
```
But that's not intuitive.

**Comment by obgm** [comment] 2021-09-20 12:18
If you have `syslog.h` on your system, configure defines `HAVE_SYSLOG_H` for you. No need to do it by yourself.
Exceptions are if you do not use aufoconf; in that case, you need to adjust `coap_config.h` according to your system.

**Comment by franzhollerer** [comment] 2021-09-20 12:23
Actually, I used cmake to build the library.

**Comment by obgm** [comment] 2021-09-20 12:36
The `CMakeLists.txt` unfortunately does a bad job mimicking what autoconf/make does; that is still a lot of work to do (good to have your input for this!). However, as autoconf/make is the primary way for building, installing and packaging libcoap, this is not high on the priority list.

**Comment by franzhollerer** [comment] 2021-09-20 13:51
> this is not high on the priority list.
That's absolutely fine for me.

**Comment by obgm** [comment] 2021-09-30 14:25
@franzhollerer With PR #750 merged, this should be fixed.

**Comment by mrdeep1** [comment] 2022-10-14 14:51
@franzhollerer If all is now working for you, can you please close this off.

**Comment by franzhollerer** [comment] 2022-10-17 12:40
Yes, PR #750 fixes the problem.

**Comment by mrdeep1** [comment] 2022-10-17 15:03
Thanks

**Closed by mrdeep1** 2022-10-17 15:03 UTC
